### ISSUE TITLE
Constrained transaction allowed to execute more than 32 instructions

### ISSUE THREAD

**Issue by ivan-w** [SDL-Hercules-390/hyperion-txf#3]
Constrained transaction shouldn't be allowed more than 32 instructions in a row. This is not enforced.

**Comment by ivan-w** [comment]
I believe that executing more than 32 instructions (TBEGINC not included) should yield a PIC X'218' (Aborted Transaction + Constrained transaction exception)

**Comment by Fish-Git** [comment]
> This is not enforced.

Huh? It _should_ be! The code is there! Why the code isn't doing its job I don't know, but the code to enforce this is definitely there! It's in the `CHECK_TXFCTR` macro:

```C
    #undef  CHECK_TXFCTR
    #define CHECK_TXFCTR( _ip, _regs )                                                    \
    do {                                                                                  \
      if (!regs->txf_level)           /* Any transaction in progress? */                  \
        break;                        /* No skip past the below logic */                  \
                                                                                          \
      regs->txf_instctr++;            /* Count instructions executed  */                  \
                                                                                          \
      /*            Too many CONSTRAINED instructions executed? */                        \
      if (1                                                                               \
        && regs->txf_contran                            /* if in CONSTRAINED mode, */     \
        && regs->txf_instctr > MAX_TXF_CONTRAN_INSTR    /* and max instr. exceeded */     \
        && memcmp( (_ip), "\xb2\xf8", 2 ) != 0          /* and not the TEND instr. */     \
      )                                                                                   \
      {                                                                                   \
        ARCH_DEP( abort_transaction )( regs, ABORT_RETRY_PGMCHK, ABORT_CODE_INSTR );      \
        UNREACHABLE_CODE(;);                                                              \
      }                                                                                   \
                                                                                          \
      /*                  Randomly abort the transaction? */                              \
      if (1                                                                               \
        && regs->txf_abortnum                                                             \
        && regs->txf_instctr == regs->txf_abortnum                                        \
      )                                                                                   \
      {                                                                                   \
        ARCH_DEP( abort_transaction )( regs, ABORT_RETRY_PGMCHK, regs->txf_rabortcode );  \
        UNREACHABLE_CODE(;);                                                              \
      }                                                                                   \
    } while(0)
```

It's the above code that causes our performance issue and prompted me to come up with the `OPTION_TXF_SLOWLOOP` build option to try and minimize its impact.

If the "32 instructions maximum" constraint is not being enforced for constrained transactions, then something _very weird_ is going on somewhere and I'm going to need some help with trying to find out what and where! &nbsp; `:(`

**Comment by ivan-w** [comment]
For reference: 

**Hercules:**
```
txft007
EXECUTING MORE THAN 32 INSTRUCTIONS.
SHOULD NOT BE HERE.
Ready(00001); T=0.01/0.01 22:58:31
```

**IBM System:**
```
txft007
EXECUTING MORE THAN 32 INSTRUCTIONS.
 -> 00000000000131F0   LR      1811
*TN 00000000000131A8       PROG    0218 -> 0001323E
        TRANSACTION ABORT + TRANSACTION CONSTRAINT
CONSTRAINED TRANSACTION EXCEPTION RAISED.
```

PS: The test is just a bunch of LR 1,1. When we reach 64 of those the test says it shouldn't have gone thus far.

**Comment by Fish-Git** [comment]
Ivan,

[**My re-write of this test**](https://github.com/Fish-Git/hyperion-fish-txf/files/4133397/TXFT00n.CORE.zip) now successfully passes when run stand-alone, _not_ under z/VM.

It is still failing the same way when run under z/VM however (code 5 = "should not be here").

Still scratching my head. &nbsp; `:(`

**Comment by Fish-Git** [comment]
_**&ast;&ast; FOUND IT! &ast;&ast;**_ &nbsp; `:-D`

_(fist pump)_

Fixed by commit cf016bd9ae6cb1b8286124c4011038f2a10d999d!

I can't believe I made such a _STUPID, careless_ mistake in the CHECK_TXFCTR macro! &nbsp;I was using _`regs`_ in the macro _instead of `(_regs)!!`_ &nbsp; _**Doh!** &nbsp; (facepalm)_

And I only managed to find _that_ bug after having added the missing OPTION_TXF_SLOWLOOP support to sie.c's run_cpu loop that I originally missed!`(*)` &nbsp; _(Doh and facepalm again!)_

Anyway... _**ALL TESTS** (except TXFT006 of course) **NOW PASS**_ in both stand-alone mode _as well as_ in SIE mode under z/VM. &nbsp; _(Yea!)_

So things are looking pretty good now, folks!

Time to start writing some more tests I guess. &nbsp; `;-)`

_______
`(*)` There's an instruction execution loop in `sie.c` too, that I had completely forgotten about, that does EXECUTE_INSTRUCTION and UNROLLED_EXECUTE just like the one in `cpu.c` does (which, when OPTION_TXF_SLOWLOOP is enabled, doesn't have a CHECK_TXFCTR macro like the TXF_EXECUTE_INSTRUCTION and TXF_UNROLLED_EXECUTE macros do).

Thus, the 32-instructions-maximum constraint was never being checked/enforced when running in SIE mode! &nbsp;_(Doh!)_

But of course it _still_ didn't work even when I added the missing OPTION_TXF_SLOWLOOP logic to sie.c's instruction loop because of my incorrectly coded CHECK_TXFCTR macro!

It was only after _both_ stupid/careless bugs were fixed that _finally_ things started working correctly.

_(Sheesh! I can be so incompetent sometimes! I guess that means I'm human? I don't know... I thought I was a Fish...)_

**Comment by ivan-w** [comment]
Lemme cross check captain!

**Comment by ivan-w** [comment]
Looks more like it!

<pre>
  <b>txft006</b>
  EXECUTING INSTRUCTIONS BEYOND 128 BYTES.
  CONSTRAINED TRANSACTION EXCEPTION RAISED.
  Ready; T=0.01/0.01 18:15:35

  <b>txft005</b>
  PERFORMING BACKWARD BRANCH IN CONSTRAINED MODE.
  CONSTRAINED TRANSACTION EXCEPTION RAISED.
  Ready; T=0.01/0.01 18:15:42

  <b>txft007</b>
  EXECUTING MORE THAN 32 INSTRUCTIONS.
  CONSTRAINED TRANSACTION EXCEPTION RAISED.
  Ready; T=0.01/0.01 18:15:47
</pre>

**Comment by ivan-w** [comment]
z/Arch SIE has gone very slow again. Like 4 times slower than ESA/390 for basic tasks. But it could be unrelated.

**Comment by Fish-Git** [comment]
> z/Arch SIE has gone very slow again. Like 4 times slower than ESA/390 for basic tasks.

Well, as I explained in my previous comment, I _did_ have to modify the SIE mode instruction execution loop in sie.c the same way that I did for the non-SIE mode loop in cpu.c (which necessarily adds an extra test-flag-and-branch statement before each instruction is executed), but I honestly can't see how that would cause a 4 times slowdown! (nor why it would impact only z/Arch SIE and not ESA/390 SIE too!)

> But it could be unrelated.

I sure hope so!

But the coincidence in the _timing_ of when this problem started occurring is somewhat _(and understandably so!)_ concerning! _(i.e. suspicious!)_ &nbsp; `:(`

Please do keep us informed and let us know if/when you find anything out. Thanks.

_(Sheesh! I hate it when things like this happen..)_
